#!/bin/sh

set -ex

# Check if the archive already exists
if [ -f "src/duckdb.tar.xz" ]; then
  echo "duckdb.tar.xz already exists. Skipping compression."
  exit 0
fi

# For CI/CD: only compress if expansion is possible too
if which xz > /dev/null; then
  if [ -d .git ]; then git clean -fdx src; fi
  cd src
  tar cvJf duckdb.tar.xz duckdb
  rm -rf duckdb
fi
