.Call(duckdb:::duckdb_load_library, system.file(c("inst","libduckdb"), package="duckdb"))
print(.Call(duckdb:::duckdb_library_version))
database <- .Call(duckdb:::duckdb_database_new)
.Call(duckdb:::duckdb_open,":memory:", database)
.Call(duckdb:::duckdb_close, database)