// Generated by package_build.py. Do not edit.
#ifndef DUCKDB_EXTENSION_PARQUET_LINKED
#define DUCKDB_EXTENSION_PARQUET_LINKED 1
#endif

#ifndef DUCKDB_EXTENSION_CORE_FUNCTIONS_LINKED
#define DUCKDB_EXTENSION_CORE_FUNCTIONS_LINKED 1
#endif

#include "duckdb/main/extension/extension_loader.hpp"
#include "duckdb_static_extension.h"

#if DUCKDB_EXTENSION_PARQUET_LINKED
#ifndef EXT_VERSION_PARQUET
#define EXT_VERSION_PARQUET ""
#endif
// Generated from extension/loader/extension_describe.c.in. Do not edit.
// Describes the parquet extension to duckdb_register_static_extension.

#include "duckdb_static_extension.h"

extern "C" void parquet_duckdb_cpp_init(duckdb::ExtensionLoader &loader);

#ifdef __cplusplus
extern "C" {
#endif

int32_t duckdb_extension_parquet_describe(duckdb_extension_descriptor *descriptor) {
	if (descriptor->version < 1) {
		descriptor->set_error(descriptor, "extension parquet needs descriptor layout 1");
		return 1;
	}
	descriptor->version = 1;
	descriptor->name = "parquet";
	descriptor->extension_version = EXT_VERSION_PARQUET;
	descriptor->api_version = "e5bc7c2c76";
	descriptor->entry_cpp = (void (*)(void))parquet_duckdb_cpp_init;
	return 0;
}

#ifdef __cplusplus
}
#endif
#endif

#if DUCKDB_EXTENSION_CORE_FUNCTIONS_LINKED
#ifndef EXT_VERSION_CORE_FUNCTIONS
#define EXT_VERSION_CORE_FUNCTIONS ""
#endif
// Generated from extension/loader/extension_describe.c.in. Do not edit.
// Describes the core_functions extension to duckdb_register_static_extension.

#include "duckdb_static_extension.h"

extern "C" void core_functions_duckdb_cpp_init(duckdb::ExtensionLoader &loader);

#ifdef __cplusplus
extern "C" {
#endif

int32_t duckdb_extension_core_functions_describe(duckdb_extension_descriptor *descriptor) {
	if (descriptor->version < 1) {
		descriptor->set_error(descriptor, "extension core_functions needs descriptor layout 1");
		return 1;
	}
	descriptor->version = 1;
	descriptor->name = "core_functions";
	descriptor->extension_version = EXT_VERSION_CORE_FUNCTIONS;
	descriptor->api_version = "e5bc7c2c76";
	descriptor->entry_cpp = (void (*)(void))core_functions_duckdb_cpp_init;
	return 0;
}

#ifdef __cplusplus
}
#endif
#endif

#ifndef DUCKDB_STATIC_EXTENSION_LOADER_API
#if defined(__GNUC__) || defined(__clang__)
#define DUCKDB_STATIC_EXTENSION_LOADER_API __attribute__((visibility("hidden")))
#else
#define DUCKDB_STATIC_EXTENSION_LOADER_API
#endif
#endif

extern "C" DUCKDB_STATIC_EXTENSION_LOADER_API int32_t duckdb_register_static_extensions(void) {
	int32_t result = 0;
#if DUCKDB_EXTENSION_PARQUET_LINKED
	if (duckdb_register_static_extension(duckdb_extension_parquet_describe) != 0) {
		result = 1;
	}
#endif
#if DUCKDB_EXTENSION_CORE_FUNCTIONS_LINKED
	if (duckdb_register_static_extension(duckdb_extension_core_functions_describe) != 0) {
		result = 1;
	}
#endif
	return result;
}
