if (Sys.getenv("CI") == "" && file.exists("../../DESCRIPTION")) {
  cpp11 <- readLines("../../R/cpp11.R")
  rx <- "(?<fun>rapi_.*) [<]- function[(](?<args>[^)]*)[)]"
  fun_lines <- grep(rx, cpp11, value = TRUE, perl = TRUE)
  funs <- rematch2::re_match(fun_lines, rx)

  code_wrappers <- paste0(
    "rethrow_", funs$fun, " <- function(", funs$args, ifelse(funs$args == "", "", ", "), "call = parent.frame(2)) {\n",
    "  rlang::try_fetch(\n",
    "    ", funs$fun, "(", funs$args, "),\n",
    "    error = function(e) {\n",
    "      rethrow_error_from_rapi(e, call)\n",
    "    }\n",
    "  )\n",
    "}"
  )

  code_restore <- paste0(
    "rethrow_restore <- function() {\n",
    paste0("  rethrow_", funs$fun, " <<- ", funs$fun, "\n", collapse = ""),
    "}"
  )

  rethrow <- paste(
    c("# Generated by helper-rethrow.R, do not edit by hand", code_wrappers, code_restore),
    collapse = "\n\n"
  )

  writeLines(rethrow, "../../R/rethrow-gen.R")
}
