test_that("relational anti_join(join_by(a)) order-enforcing 2", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  invisible(
    dbExecute(con, 'CREATE MACRO "___eq_na_matches_na"(x, y) AS (x IS NOT DISTINCT FROM y)')
  )
  df1 <- data.frame(a = 1:4, b = 2)
  "anti_join"
  df2 <- rel_set_alias2(df1, con, "lhs")
  df3 <- data.frame(a = 2:5, b = 2)
  "anti_join"
  df4 <- rel_set_alias2(df3, con, "rhs")
  "anti_join"
  df5 <- rel_join2(
    df2,
    df4,
    con,
    list(
      expr_function("___eq_na_matches_na", list(expr_reference2("a", df2, con), expr_reference2("a", df4, con)))
    ),
    "anti"
  )
  "anti_join"
  df6 <- rel_order2(df5, con, list(expr_reference("a"), expr_reference("b")))
  df6
  expect_identical(
    df6,
    data.frame(a = 1L, b = 2)
  )
  dbDisconnect(con, shutdown = TRUE)
})

test_that("relational anti_join(join_by(a)) order-enforcing 2", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  invisible(
    dbExecute(con, 'CREATE MACRO "___eq_na_matches_na"(x, y) AS (x IS NOT DISTINCT FROM y)')
  )
  df1 <- data.frame(a = 1:4, b = 2)
  "anti_join"
  df2 <- rel_set_alias2(df1, con, "lhs")
  df3 <- data.frame(a = 2:5, b = 2)
  "anti_join"
  df4 <- rel_set_alias2(df3, con, "rhs")
  "anti_join"
  df5 <- rel_join2(
    df2,
    df4,
    con,
    list(
      expr_function("___eq_na_matches_na", list(expr_reference2("a", df2, con), expr_reference2("a", df4, con)))
    ),
    "anti"
  )
  "arrange"
  df6 <- rel_order2(df5, con, list(expr_reference("a"), expr_reference("b")))
  df6
  expect_identical(
    df6,
    data.frame(a = 1L, b = 2)
  )
  dbDisconnect(con, shutdown = TRUE)
})

test_that("relational arrange(a) order-preserving 2", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  df1 <- data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))

  "arrange"
  df2 <- rel_project2(
    df1,
    con,
    list(
      {
        tmp_expr <- expr_reference2("a")
        expr_set_alias(tmp_expr, "a")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference2("b")
        expr_set_alias(tmp_expr, "b")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference2("g")
        expr_set_alias(tmp_expr, "g")
        tmp_expr
      },
      {
        tmp_expr <- expr_window(expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        expr_set_alias(tmp_expr, "___row_number")
        tmp_expr
      }
    )
  )
  "arrange"
  df3 <- rel_order2(df2, con, list(expr_reference2("a"), expr_reference2("___row_number")))
  "arrange"
  df4 <- rel_project2(
    df3,
    con,
    list(
      {
        tmp_expr <- expr_reference("a")
        expr_set_alias(tmp_expr, "a")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("b")
        expr_set_alias(tmp_expr, "b")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("g")
        expr_set_alias(tmp_expr, "g")
        tmp_expr
      }
    )
  )
  expect_identical(
    df4,
    data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))
  )
  dbDisconnect(con, shutdown = TRUE)
})

test_that("relational arrange(g) order-enforcing 2", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  df1 <- data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))

  "arrange"
  df2 <- rel_project2(
    df1,
    con,
    list(
      {
        tmp_expr <- expr_reference("a")
        expr_set_alias(tmp_expr, "a")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("b")
        expr_set_alias(tmp_expr, "b")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("g")
        expr_set_alias(tmp_expr, "g")
        tmp_expr
      },
      {
        tmp_expr <- expr_window(expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        expr_set_alias(tmp_expr, "___row_number")
        tmp_expr
      }
    )
  )
  "arrange"
  df3 <- rel_order2(df2, con, list(expr_reference("g"), expr_reference("___row_number")))
  "arrange"
  df4 <- rel_project2(
    df3,
    con,
    list(
      {
        tmp_expr <- expr_reference("a")
        expr_set_alias(tmp_expr, "a")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("b")
        expr_set_alias(tmp_expr, "b")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("g")
        expr_set_alias(tmp_expr, "g")
        tmp_expr
      }
    )
  )
  expect_identical(
    df4,
    data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))
  )
  dbDisconnect(con, shutdown = TRUE)
})

test_that("relational arrange() order-enforcing 2", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  df1 <- data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))

  "arrange"
  df2 <- rel_order2(
    df1,
    con,
    list(expr_reference("a"), expr_reference("b"), expr_reference("g"))
  )
  expect_identical(
    df2,
    data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))
  )
  dbDisconnect(con, shutdown = TRUE)
})

test_that("relational arrange(a) order-enforcing 2", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  df1 <- data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))

  "arrange"
  df2 <- rel_order2(
    df1,
    con,
    list(expr_reference("a"), expr_reference("b"), expr_reference("g"))
  )
  expect_identical(
    df2,
    data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))
  )
  dbDisconnect(con, shutdown = TRUE)
})

test_that("relational arrange(g) order-enforcing 2", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  df1 <- data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))

  "arrange"
  rel1 <- rel_from_df(con, df1, experimental = experimental)
  "arrange"
  rel2 <- rel_order(rel1, list(expr_reference("g")))
  "arrange"
  rel3 <- rel_order(
    rel2,
    list(expr_reference("a"), expr_reference("b"), expr_reference("g"))
  )
  rel3
  out <- rel_to_altrep(rel3)
  expect_identical(
    out,
    data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))
  )
  dbDisconnect(con, shutdown = TRUE)
})

test_that("relational arrange(g, a) order-enforcing 2", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  df1 <- data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))

  "arrange"
  rel1 <- rel_from_df(con, df1, experimental = experimental)
  "arrange"
  rel2 <- rel_order(rel1, list(expr_reference("g"), expr_reference("a")))
  "arrange"
  rel3 <- rel_order(
    rel2,
    list(expr_reference("a"), expr_reference("b"), expr_reference("g"))
  )
  rel3
  out <- rel_to_altrep(rel3)
  expect_identical(
    out,
    data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))
  )
  dbDisconnect(con, shutdown = TRUE)
})

test_that("relational arrange(a, g) order-enforcing 2", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  df1 <- data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))

  df2 <- rel_order2(
    df1,
    con,
    list(expr_reference("a"), expr_reference("b"), expr_reference("g"))
  )
  expect_identical(
    df2,
    data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))
  )
  dbDisconnect(con, shutdown = TRUE)
})

test_that("relational count() order-preserving 2", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  invisible(dbExecute(con, 'CREATE MACRO "n"() AS CAST(COUNT(*) AS int32)'))
  df1 <- data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))

  "count"
  df2 <- rel_aggregate2(
    df1,
    con,
    groups = list(),
    aggregates = list(
      {
        tmp_expr <- expr_function("n", list())
        expr_set_alias(tmp_expr, "n")
        tmp_expr
      }
    )
  )
  expect_identical(
    df2,
    data.frame(n = 6L)
  )
  dbDisconnect(con, shutdown = TRUE)
})

test_that("relational count(a) order-preserving 2", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  invisible(dbExecute(con, 'CREATE MACRO "n"() AS CAST(COUNT(*) AS int32)'))
  df1 <- data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))

  "count"
  df2 <- rel_aggregate2(
    df1,
    con,
    groups = list(
      a = {
        tmp_expr <- expr_reference("a")
        expr_set_alias(tmp_expr, "a")
        tmp_expr
      }
    ),
    aggregates = list(
      {
        tmp_expr <- expr_function("n", list())
        expr_set_alias(tmp_expr, "n")
        tmp_expr
      }
    )
  )
  "count"
  df3 <- rel_order2(
    df2,
    con,
    list(
      {
        tmp_expr <- expr_reference("a")
        expr_set_alias(tmp_expr, "a")
        tmp_expr
      }
    )
  )
  expect_identical(
    df3,
    data.frame(a = seq(1, 6, by = 1), n = 1L)
  )
  dbDisconnect(con, shutdown = TRUE)
})

test_that("relational count(b) order-preserving 2", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  invisible(dbExecute(con, 'CREATE MACRO "n"() AS CAST(COUNT(*) AS int32)'))
  df1 <- data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))

  "count"
  df2 <- rel_aggregate2(
    df1,
    con,
    groups = list(
      b = {
        tmp_expr <- expr_reference("b")
        expr_set_alias(tmp_expr, "b")
        tmp_expr
      }
    ),
    aggregates = list(
      {
        tmp_expr <- expr_function("n", list())
        expr_set_alias(tmp_expr, "n")
        tmp_expr
      }
    )
  )
  "count"
  df3 <- rel_order2(
    df2,
    con,
    list(
      {
        tmp_expr <- expr_reference("b")
        expr_set_alias(tmp_expr, "b")
        tmp_expr
      }
    )
  )
  expect_identical(
    df3,
    data.frame(b = 2, n = 6L)
  )
  dbDisconnect(con, shutdown = TRUE)
})

test_that("relational distinct() order-preserving 2", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  df1 <- data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))

  "distinct"
  df2 <- rel_project2(
    df1,
    con,
    list(
      {
        tmp_expr <- expr_reference("a")
        expr_set_alias(tmp_expr, "a")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("b")
        expr_set_alias(tmp_expr, "b")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("g")
        expr_set_alias(tmp_expr, "g")
        tmp_expr
      },
      {
        tmp_expr <- expr_window(expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        expr_set_alias(tmp_expr, "___row_number")
        tmp_expr
      }
    )
  )
  "distinct"
  df3 <- rel_project2(
    df2,
    con,
    list(
      {
        tmp_expr <- expr_reference("a")
        expr_set_alias(tmp_expr, "a")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("b")
        expr_set_alias(tmp_expr, "b")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("g")
        expr_set_alias(tmp_expr, "g")
        tmp_expr
      },
      expr_reference("___row_number"),
      {
        tmp_expr <- expr_window(
          expr_function("row_number", list()),
          list(
            a = {
              tmp_expr <- expr_reference("a")
              expr_set_alias(tmp_expr, "a")
              tmp_expr
            },
            b = {
              tmp_expr <- expr_reference("b")
              expr_set_alias(tmp_expr, "b")
              tmp_expr
            },
            g = {
              tmp_expr <- expr_reference("g")
              expr_set_alias(tmp_expr, "g")
              tmp_expr
            }
          ),
          list(expr_reference("___row_number")),
          offset_expr = NULL,
          default_expr = NULL
        )
        expr_set_alias(tmp_expr, "___row_number_by")
        tmp_expr
      }
    )
  )
  "distinct"
  df4 <- rel_filter2(
    df3,
    con,
    list(
      expr_comparison(
        "==",
        list(
          expr_reference("___row_number_by"),
          if ("experimental" %in% names(formals(expr_constant))) {
            expr_constant(1L, experimental = experimental)
          } else {
            expr_constant(1L)
          }
        )
      )
    )
  )
  "distinct"
  df5 <- rel_order2(df4, con, list(expr_reference("___row_number")))
  "distinct"
  df6 <- rel_project2(
    df5,
    con,
    list(
      {
        tmp_expr <- expr_reference("a")
        expr_set_alias(tmp_expr, "a")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("b")
        expr_set_alias(tmp_expr, "b")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("g")
        expr_set_alias(tmp_expr, "g")
        tmp_expr
      }
    )
  )
  expect_identical(
    df6,
    data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))
  )
  dbDisconnect(con, shutdown = TRUE)
})

test_that("relational distinct(a) order-preserving 2", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  df1 <- data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))

  "distinct"
  df2 <- rel_project2(
    df1,
    con,
    list(
      {
        tmp_expr <- expr_reference("a")
        expr_set_alias(tmp_expr, "a")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("b")
        expr_set_alias(tmp_expr, "b")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("g")
        expr_set_alias(tmp_expr, "g")
        tmp_expr
      },
      {
        tmp_expr <- expr_window(expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        expr_set_alias(tmp_expr, "___row_number")
        tmp_expr
      }
    )
  )
  "distinct"
  df3 <- rel_project2(
    df2,
    con,
    list(
      {
        tmp_expr <- expr_reference("a")
        expr_set_alias(tmp_expr, "a")
        tmp_expr
      },
      expr_reference("___row_number"),
      {
        tmp_expr <- expr_window(
          expr_function("row_number", list()),
          list(
            a = {
              tmp_expr <- expr_reference("a")
              expr_set_alias(tmp_expr, "a")
              tmp_expr
            }
          ),
          list(expr_reference("___row_number")),
          offset_expr = NULL,
          default_expr = NULL
        )
        expr_set_alias(tmp_expr, "___row_number_by")
        tmp_expr
      }
    )
  )
  "distinct"
  df4 <- rel_filter2(
    df3,
    con,
    list(
      expr_comparison(
        "==",
        list(
          expr_reference("___row_number_by"),
          if ("experimental" %in% names(formals(expr_constant))) {
            expr_constant(1L, experimental = experimental)
          } else {
            expr_constant(1L)
          }
        )
      )
    )
  )
  "distinct"
  df5 <- rel_order2(df4, con, list(expr_reference("___row_number")))
  "distinct"
  df6 <- rel_project2(
    df5,
    con,
    list(
      {
        tmp_expr <- expr_reference("a")
        expr_set_alias(tmp_expr, "a")
        tmp_expr
      }
    )
  )
  expect_identical(
    df6,
    data.frame(a = seq(1, 6, by = 1))
  )
  dbDisconnect(con, shutdown = TRUE)
})

test_that("relational union_all(data.frame(a = 1L, b = 3, g = 2L)) %>% distinct(g) order-preserving", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  df1 <- data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))

  "union_all"
  df2 <- rel_project2(
    df1,
    con,
    list(
      {
        tmp_expr <- expr_reference("a")
        expr_set_alias(tmp_expr, "a")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("b")
        expr_set_alias(tmp_expr, "b")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("g")
        expr_set_alias(tmp_expr, "g")
        tmp_expr
      },
      {
        tmp_expr <- expr_window(expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        expr_set_alias(tmp_expr, "___row_number_x")
        tmp_expr
      },
      {
        tmp_expr <- if ("experimental" %in% names(formals(expr_constant))) {
          expr_constant(NA_integer_, experimental = experimental)
        } else {
          expr_constant(NA_integer_)
        }
        expr_set_alias(tmp_expr, "___row_number_y")
        tmp_expr
      }
    )
  )
  "union_all"
  df3 <- rel_project2(
    df2,
    con,
    list(
      {
        tmp_expr <- expr_reference("a")
        expr_set_alias(tmp_expr, "a")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("b")
        expr_set_alias(tmp_expr, "b")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("g")
        expr_set_alias(tmp_expr, "g")
        tmp_expr
      },
      {
        tmp_expr <- if ("experimental" %in% names(formals(expr_constant))) {
          expr_constant(NA_integer_, experimental = experimental)
        } else {
          expr_constant(NA_integer_)
        }
        expr_set_alias(tmp_expr, "___row_number_x")
        tmp_expr
      },
      {
        tmp_expr <- expr_window(expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        expr_set_alias(tmp_expr, "___row_number_y")
        tmp_expr
      }
    )
  )
  "union_all"
  df4 <- rel_union_all2(df2, df3, con)
  "union_all"
  df5 <- rel_order2(
    df4,
    con,
    list(expr_reference("___row_number_x"), expr_reference("___row_number_y"))
  )
  "union_all"
  df6 <- rel_project2(
    df5,
    con,
    list(
      {
        tmp_expr <- expr_reference("a")
        expr_set_alias(tmp_expr, "a")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("b")
        expr_set_alias(tmp_expr, "b")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("g")
        expr_set_alias(tmp_expr, "g")
        tmp_expr
      }
    )
  )
  "distinct"
  df7 <- rel_project2(
    df6,
    con,
    list(
      {
        tmp_expr <- expr_reference("a")
        expr_set_alias(tmp_expr, "a")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("b")
        expr_set_alias(tmp_expr, "b")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("g")
        expr_set_alias(tmp_expr, "g")
        tmp_expr
      },
      {
        tmp_expr <- expr_window(expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        expr_set_alias(tmp_expr, "___row_number")
        tmp_expr
      }
    )
  )
  "distinct"
  df8 <- rel_project2(
    df7,
    con,
    list(
      {
        tmp_expr <- expr_reference("g")
        expr_set_alias(tmp_expr, "g")
        tmp_expr
      },
      expr_reference("___row_number"),
      {
        tmp_expr <- expr_window(
          expr_function("row_number", list()),
          list(
            g = {
              tmp_expr <- expr_reference("g")
              expr_set_alias(tmp_expr, "g")
              tmp_expr
            }
          ),
          list(expr_reference("___row_number")),
          offset_expr = NULL,
          default_expr = NULL
        )
        expr_set_alias(tmp_expr, "___row_number_by")
        tmp_expr
      }
    )
  )
  "distinct"
  df9 <- rel_filter2(
    df8,
    con,
    list(
      expr_comparison(
        "==",
        list(
          expr_reference("___row_number_by"),
          if ("experimental" %in% names(formals(expr_constant))) {
            expr_constant(1L, experimental = experimental)
          } else {
            expr_constant(1L)
          }
        )
      )
    )
  )
  "distinct"
  df10 <- rel_order2(df9, con, list(expr_reference("___row_number")))
  "distinct"
  df11 <- rel_project2(
    df10,
    con,
    list(
      {
        tmp_expr <- expr_reference("g")
        expr_set_alias(tmp_expr, "g")
        tmp_expr
      }
    )
  )
  expect_identical(
    df11,
    data.frame(g = 1:3)
  )
  dbDisconnect(con, shutdown = TRUE)
})

test_that("relational filter(a == 1) order-enforcing", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  df1 <- data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))

  "filter"
  df2 <- rel_filter2(
    df1,
    con,
    list(
      expr_comparison(
        "==",
        list(
          expr_reference("a"),
          if ("experimental" %in% names(formals(expr_constant))) {
            expr_constant(1, experimental = experimental)
          } else {
            expr_constant(1)
          }
        )
      )
    )
  )
  "arrange"
  df3 <- rel_order2(
    df2,
    con,
    list(expr_reference("a"), expr_reference("b"), expr_reference("g"))
  )
  expect_identical(
    df3,
    data.frame(a = 1, b = 2, g = 1L)
  )
  dbDisconnect(con, shutdown = TRUE)
})

test_that("relational filter(a %in% 2:3 & g == 2) order-enforcing", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  invisible(rapi_load_rfuns(drv@database_ref))
  invisible(dbExecute(con, 'CREATE MACRO "&"(x, y) AS (x AND y)'))
  invisible(dbExecute(con, 'CREATE MACRO "___coalesce"(x, y) AS COALESCE(x, y)'))
  invisible(dbExecute(con, 'CREATE MACRO "|"(x, y) AS (x OR y)'))
  df1 <- data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))

  "filter"
  df2 <- rel_filter2(
    df1,
    con,
    list(
      expr_function(
        "&",
        list(
          expr_function(
            "___coalesce",
            list(
              expr_function(
                "|",
                list(
                  expr_function(
                    "r_base::==",
                    list(
                      expr_reference("a"),
                      if ("experimental" %in% names(formals(expr_constant))) {
                        expr_constant(2L, experimental = experimental)
                      } else {
                        expr_constant(2L)
                      }
                    )
                  ),
                  expr_function(
                    "r_base::==",
                    list(
                      expr_reference("a"),
                      if ("experimental" %in% names(formals(expr_constant))) {
                        expr_constant(3L, experimental = experimental)
                      } else {
                        expr_constant(3L)
                      }
                    )
                  )
                )
              ),
              if ("experimental" %in% names(formals(expr_constant))) {
                expr_constant(FALSE, experimental = experimental)
              } else {
                expr_constant(FALSE)
              }
            )
          ),
          expr_comparison(
            "==",
            list(
              expr_reference("g"),
              if ("experimental" %in% names(formals(expr_constant))) {
                expr_constant(2, experimental = experimental)
              } else {
                expr_constant(2)
              }
            )
          )
        )
      )
    )
  )
  "arrange"
  df3 <- rel_order2(
    df2,
    con,
    list(expr_reference("a"), expr_reference("b"), expr_reference("g"))
  )
  expect_identical(
    df3,
    data.frame(a = c(2, 3), b = 2, g = 2L)
  )
  dbDisconnect(con, shutdown = TRUE)
})

#
test_that("relational summarise(c = mean(a)) order-enforcing", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  df1 <- data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))

  "summarise"
  df2 <- rel_aggregate2(
    df1,
    con,
    groups = list(),
    aggregates = list(
      {
        tmp_expr <- expr_function("mean", list(expr_reference("a")))
        expr_set_alias(tmp_expr, "c")
        tmp_expr
      }
    )
  )
  "summarise"
  df3 <- rel_distinct2(df2, con)
  "arrange"
  df4 <- rel_order2(df3, con, list(expr_reference("c")))
  expect_identical(
    df4,
    data.frame(c = 3.5)
  )
  dbDisconnect(con, shutdown = TRUE)
})

test_that("relational summarise(c = mean(a), .by = b) order-enforcing", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  df1 <- data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))

  "summarise"
  df2 <- rel_aggregate2(
    df1,
    con,
    groups = list(expr_reference("b")),
    aggregates = list(
      {
        tmp_expr <- expr_function("mean", list(expr_reference("a")))
        expr_set_alias(tmp_expr, "c")
        tmp_expr
      }
    )
  )
  "arrange"
  df3 <- rel_order2(df2, con, list(expr_reference("b"), expr_reference("c")))
  expect_identical(
    df3,
    data.frame(b = 2, c = 3.5)
  )
  dbDisconnect(con, shutdown = TRUE)
})

test_that("relational summarise(c = mean(a), .by = g) order-enforcing", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  df1 <- data.frame(a = seq(1, 6, by = 1), b = 2, g = c(1L, 2L, 2L, 3L, 3L, 3L))

  "summarise"
  df2 <- rel_aggregate2(
    df1,
    con,
    groups = list(expr_reference("g")),
    aggregates = list(
      {
        tmp_expr <- expr_function("mean", list(expr_reference("a")))
        expr_set_alias(tmp_expr, "c")
        tmp_expr
      }
    )
  )
  "arrange"
  df3 <- rel_order2(df2, con, list(expr_reference("g"), expr_reference("c")))
  expect_identical(
    df3,
    data.frame(g = 1:3, c = c(1, 2.5, 5))
  )
  dbDisconnect(con, shutdown = TRUE)
})

test_that("relational intersect() order-enforcing", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  df1 <- data.frame(a = 1:4, b = 2)
  df2 <- data.frame(a = 2:5, b = 2)

  "intersect"
  df3 <- rel_set_intersect2(df1, df2, con)
  "arrange"
  df4 <- rel_order2(df3, con, list(expr_reference("a"), expr_reference("b")))
  expect_identical(
    df4,
    data.frame(a = 2:4, b = 2)
  )
  dbDisconnect(con, shutdown = TRUE)
})

test_that("relational setdiff() order-enforcing", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  df1 <- data.frame(a = 1:4, b = 2)
  df2 <- data.frame(a = 2:5, b = 2)

  "setdiff"
  df3 <- rel_set_diff2(df1, df2, con)
  "arrange"
  df4 <- rel_order2(df3, con, list(expr_reference("a"), expr_reference("b")))
  expect_identical(
    df4,
    data.frame(a = 1L, b = 2)
  )
  dbDisconnect(con, shutdown = TRUE)
})

test_that("relational symdiff() order-enforcing", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  df1 <- data.frame(a = 1:4, b = 2)
  df2 <- data.frame(a = 2:5, b = 2)

  "symdiff"
  df3 <- rel_set_symdiff2(df1, df2, con)
  "arrange"
  df4 <- rel_order2(df3, con, list(expr_reference("a"), expr_reference("b")))
  expect_identical(
    df4,
    data.frame(a = c(1L, 5L), b = 2)
  )
  dbDisconnect(con, shutdown = TRUE)
})
