test_that("relational anti_join(join_by(a)) order-preserving 2", {
  # Autogenerated
  drv <- duckdb()
  con <- dbConnect(drv)
  experimental <- FALSE
  invisible(
    dbExecute(con, 'CREATE MACRO "___eq_na_matches_na"(x, y) AS (x IS NOT DISTINCT FROM y)')
  )
  df1 <- data.frame(a = 1:4, b = 2)
  "anti_join"
  df2 <- rel_set_alias2(df1, con, "lhs")
  df3 <- data.frame(a = 2:5, b = 2)
  "anti_join"
  df4 <- rel_set_alias2(df3, con, "rhs")
  "anti_join"
  df5 <- rel_project2(
    df2,
    con,
    list(
      {
        tmp_expr <- expr_reference("a")
        expr_set_alias(tmp_expr, "a")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("b")
        expr_set_alias(tmp_expr, "b")
        tmp_expr
      },
      {
        tmp_expr <- expr_window(expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        expr_set_alias(tmp_expr, "___row_number_x")
        tmp_expr
      }
    )
  )
  "anti_join"
  df6 <- rel_join2(
    df5,
    df4,
    con,
    list(
      expr_function("___eq_na_matches_na", list(expr_reference("a", rel5), expr_reference("a", rel4)))
    ),
    "anti"
  )
  "anti_join"
  df7 <- rel_order2(df6, con, list(expr_reference("___row_number_x", rel5)))
  "anti_join"
  df8 <- rel_project2(
    df7,
    con,
    list(
      {
        tmp_expr <- expr_reference("a")
        expr_set_alias(tmp_expr, "a")
        tmp_expr
      },
      {
        tmp_expr <- expr_reference("b")
        expr_set_alias(tmp_expr, "b")
        tmp_expr
      }
    )
  )
  df8
  expect_identical(
    df8,
    data.frame(a = 1L, b = 2)
  )
  dbDisconnect(con, shutdown = TRUE)
})
