# Handbook: handbook/contributors/debugging/README.md
FROM wch1/r-debug

WORKDIR /root

COPY docker/r-debug-strictbarrier.sh docker/deps.R DESCRIPTION .

RUN ./r-debug-strictbarrier.sh

WORKDIR /root/workspace

ENTRYPOINT /bin/bash
