"""Regenerate the vendored build configuration from a DuckDB checkout:
src/duckdb/, src/include/sources.mk, R/version.R, the Makevars files and
the logos.

The logos land in man/figures/. Called by vendor.sh and vendor-one.sh
with DUCKDB_PATH set.
"""
import os
import re
import shutil
import sys
import platform

extensions = ['parquet','core_functions']

if 'DUCKDB_R_EXTENSIONS' in os.environ:
    extensions = extensions + os.environ['DUCKDB_R_EXTENSIONS'].split(",")

debug_move_flag = ''
if 'DUCKDB_DEBUG_MOVE' in os.environ:
    debug_move_flag = ' -DDUCKDB_DEBUG_MOVE'

# Submodules can't be used for the DuckDB checkout because they break R CMD build.
if 'DUCKDB_PATH' in os.environ:
    duckdb_path = os.environ['DUCKDB_PATH']
else:
    duckdb_path = os.path.join('../duckdb')

def extract_version_info():
    """Extract version info from duckdb sources if available."""
    pragma_version_path = os.path.join('src', 'duckdb', 'src', 'function', 'table', 'version', 'pragma_version.cpp')
    version = None
    with open(pragma_version_path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line.startswith('#define DUCKDB_VERSION'):
                # Extract version string, e.g., from '#define DUCKDB_VERSION "v1.3.3-dev231"'
                parts = line.split('"')
                if len(parts) >= 2:
                    version = parts[1]
                    # Remove 'v' prefix for consistency with R test expectations
                    if version.startswith('v'):
                        version = version[1:]
                    break

    return version

def generate_version_r_file(version):
    """Generate R file with hard-coded version information."""
    if version:
        r_version_content = f'''# Generated by rconfigure.py, do not edit by hand
# DuckDB version information

duckdb_version <- "{version}"

# Function to get DuckDB version without establishing a connection
get_duckdb_version <- function() {{
  duckdb_version
}}
'''

        with open(os.path.join('R', 'version.R'), 'w', encoding='utf-8') as f:
            f.write(r_version_content)


# The logos the package shows, and the only files this script takes from
# upstream that are not sources. They ride along with the vendored commit so
# what a reader sees cannot drift from the engine it documents: the previous
# README hotlinked duckdb.org, those URLs went away, and GitHub -- which
# proxies README images and serves nothing for a URL it cannot fetch -- showed
# no logo at all until the files were vendored.
#
# The horizontal pair keeps its upstream name; the stacked pair is the package
# logo, and pkgdown finds that one by the name man/figures/logo.svg rather than
# by configuration, so the rename is not ours to choose.
logo_files = [
    ('DuckDB_Logo-horizontal.svg', 'DuckDB_Logo-horizontal.svg'),
    ('DuckDB_Logo-horizontal-dark-mode.svg', 'DuckDB_Logo-horizontal-dark-mode.svg'),
    ('DuckDB_Logo-stacked.svg', 'logo.svg'),
    ('DuckDB_Logo-stacked-dark-mode.svg', 'logo-dark-mode.svg'),
]


def copy_logos():
    """Copy the logos from the DuckDB checkout into man/figures/."""
    source_dir = os.path.join(duckdb_path, 'logo')
    target_dir = os.path.join('man', 'figures')

    for name, target in logo_files:
        source = os.path.join(source_dir, name)
        if not os.path.isfile(source):
            print("Could not find logo {}!".format(source))
            print("  Update logo_files here and README.md together.")
            exit(1)
        shutil.copyfile(source, os.path.join(target_dir, target))

# jemalloc, the allocator DuckDB's own build uses on the platforms it supports
# it on. Upstream keeps it in third_party/jemalloc/, and its amalgamation lists
# only the DuckDB-side wrapper (src/common/allocator/allocator_jemalloc.cpp) --
# the allocator itself is a CMake target (third_party/jemalloc/CMakeLists.txt)
# that package_build.py never walks. So copy the tree here, the way
# build_package copies the sources it does know about.
#
# src/jemalloc_cpp.cpp is left behind deliberately: it overrides global new and
# delete, which is DuckDB's OVERRIDE_NEW_DELETE build option and not something
# an R package may do to the process it is loaded into. The DuckDB Java client
# excludes it from its vendoring for the same reason.
#
# Only sources and headers travel, matching what the rest of the vendored tree
# carries -- no CMakeLists.txt, and no LICENSE, because the licence terms ride
# in the package's own LICENSE and DESCRIPTION instead.
jemalloc_dir = os.path.join('third_party', 'jemalloc')
jemalloc_skip = ['jemalloc_cpp.cpp']


def vendor_jemalloc(target_dir):
    """Copy the jemalloc tree into the vendored engine.

    Returns the absolute paths of the C sources it copied, which the caller
    keeps in a make variable of their own.
    """
    source_root = os.path.join(duckdb_path, jemalloc_dir)
    if not os.path.isdir(source_root):
        print("Could not find the jemalloc sources at {}!".format(source_root))
        print("  DuckDB moved or dropped third_party/jemalloc; update rconfigure.py.")
        exit(1)

    target_root = os.path.join(target_dir, jemalloc_dir)
    sources = []
    for root, dirs, files in os.walk(source_root):
        dirs.sort()
        relative = os.path.relpath(root, source_root)
        out_dir = target_root if relative == os.curdir else os.path.join(target_root, relative)
        if not os.path.isdir(out_dir):
            os.makedirs(out_dir)
        for name in sorted(files):
            if name in jemalloc_skip:
                continue
            if not name.endswith('.c') and not name.endswith('.h'):
                continue
            out_file = os.path.join(out_dir, name)
            shutil.copyfile(os.path.join(root, name), out_file)
            if name.endswith('.c'):
                sources.append(out_file)

    # Every .c in the tree is one jemalloc's own CMakeLists.txt compiles, so the
    # walk above needs no roster of its own -- but that is a property of the
    # upstream tree and not a rule, so say so here rather than find out from a
    # build. A file upstream ships and does not compile would otherwise be
    # compiled silently, and one it compiles from elsewhere would go missing.
    listed = set(re.findall(r'src/([A-Za-z0-9_]+\.c)\b', read_jemalloc_roster(source_root)))
    copied = set(os.path.basename(x) for x in sources)
    if listed != copied:
        print("The jemalloc sources and third_party/jemalloc/CMakeLists.txt disagree.")
        print("  only in CMakeLists.txt: {}".format(sorted(listed - copied)))
        print("  only in src/:           {}".format(sorted(copied - listed)))
        print("  Update rconfigure.py to match what upstream compiles.")
        exit(1)

    return sources


def read_jemalloc_roster(source_root):
    """The JEMALLOC_C_FILES block of jemalloc's CMakeLists.txt."""
    cmakelists = os.path.join(source_root, 'CMakeLists.txt')
    if not os.path.isfile(cmakelists):
        print("Could not find {}!".format(cmakelists))
        exit(1)
    with open_utf8(cmakelists, 'r') as f:
        text = f.read()
    if 'set(JEMALLOC_C_FILES' not in text:
        print("{} no longer declares JEMALLOC_C_FILES.".format(cmakelists))
        exit(1)
    return text.split('set(JEMALLOC_C_FILES', 1)[1].split(')', 1)[0]


sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', duckdb_path, 'scripts'))
import package_build


def open_utf8(fpath, flags):
    import sys

    if sys.version_info[0] < 3:
        return open(fpath, flags)
    else:
        return open(fpath, flags, encoding="utf8")


extension_list = ""

for ext in extensions:
    extension_list += ' -DDUCKDB_EXTENSION_{}_LINKED'.format(ext.upper())
    extension_list += " -DDUCKDB_BUILD_LIBRARY"

libraries = []
if platform.system() == 'Windows':
    libraries += ['ws2_32']

link_flags = ''
for libname in libraries:
    link_flags += ' -l' + libname

if not os.path.isfile(os.path.join(duckdb_path, 'scripts', 'amalgamation.py')):
    print("Could not find amalgamation script!")
    exit(1)

# Before the regeneration below, so a checkout that cannot supply them fails
# in a second rather than after ~3550 files have been rewritten.
copy_logos()

target_dir = os.path.join(os.getcwd(), 'src', 'duckdb')

# Where the tree this run replaces is kept while the new one is generated.
#
# The regeneration itself is unavoidable, but rewriting a file is not free after
# the write: it invalidates git's stat cache entry for it, so every later git
# command over the tree re-hashes all ~3550 files. `git status` measured 1.06 s
# right after every file was touched against 0.017 s with the index still valid,
# and a vendor run pays that twice per candidate -- once for the "more than one
# changed file" test that decides whether the candidate is worth a commit, and
# once for `git add` -- whether or not the candidate is kept.
#
# So the old tree is moved aside rather than deleted, and every regenerated file
# that turns out to be byte-identical to its predecessor is replaced by that
# predecessor: `os.replace` puts the original inode back, with the size, mtime
# and ctime the index recorded, and the stat cache entry is valid again. The
# tree left behind is byte-for-byte what a regeneration from scratch produces,
# because that is what it was compared against; only the inodes below the
# unchanged majority are older than the run.
previous_dir = os.path.join(os.getcwd(), 'src', '.duckdb-previous')


def files_equal(a, b):
    """Do these two paths hold the same bytes? A missing `b` is not equal."""
    if not os.path.isfile(b):
        return False
    if os.path.getsize(a) != os.path.getsize(b):
        return False
    with open(a, 'rb') as fa, open(b, 'rb') as fb:
        return fa.read() == fb.read()


def restore_unchanged(previous, target):
    """Put back the inode of every regenerated file that did not change.

    Returns (restored, rewritten).
    """
    restored = rewritten = 0
    for root, dirs, files in os.walk(target):
        rel = os.path.relpath(root, target)
        previous_root = previous if rel == os.curdir else os.path.join(previous, rel)
        for name in files:
            current = os.path.join(root, name)
            before = os.path.join(previous_root, name)
            if files_equal(current, before):
                os.replace(before, current)
                restored += 1
            else:
                rewritten += 1
    return restored, rewritten


# A run that died between the move and the regeneration leaves the tree here and
# nothing at target_dir; put it back rather than dropping it on the floor.
if os.path.isdir(previous_dir) and not os.path.isdir(target_dir):
    os.rename(previous_dir, target_dir)
shutil.rmtree(previous_dir, ignore_errors=True)
if os.path.isdir(target_dir):
    os.rename(target_dir, previous_dir)

linenr = bool(os.getenv("DUCKDB_R_LINENR", ""))

(source_list, include_list, original_sources) = package_build.build_package(target_dir, extensions, linenr)

# The amalgamation lists src/common/allocator/allocator_jemalloc.cpp but not
# the allocator it wraps, so vendor that tree here and keep its sources apart
# from the rest: whether they are compiled at all is ./configure's decision,
# taken on the build machine, and not one this script can take for it.
source_list = [x for x in source_list if 'third_party/jemalloc' not in x.replace('\\', '/')]
jemalloc_sources = vendor_jemalloc(target_dir)

# Walk target_dir, find all source and include files, and terminate with newline,
# if not already present. Before the restore below, so what it compares against
# is the final content of each file.
for root, dirs, files in os.walk(target_dir):
    for file in files:
        if file.endswith('.cpp') or file.endswith('.hpp') or file.endswith('.c') or file.endswith('.h') or file.endswith('.cc'):
            filename = os.path.join(root, file)
            with open (filename, "r") as f:
                lines = f.readlines()
                if len(lines) > 0 and lines[-1][-1] != '\n':
                    with open (filename, "a") as fw:
                        fw.write("\n")

restored, rewritten = restore_unchanged(previous_dir, target_dir)
shutil.rmtree(previous_dir, ignore_errors=True)
print("Vendored tree: {} files changed, {} unchanged".format(rewritten, restored))

script_path = os.path.dirname(os.path.abspath(__file__)).replace('\\', '/')

root_path = os.path.dirname(script_path)

def object_list_of(sources):
    relative = [package_build.get_relative_path(os.path.join(root_path, 'src'), x) for x in sources]
    return ' '.join([x.rsplit('.', 1)[0] + '.o' for x in sorted(relative)])


object_list = object_list_of(source_list)
jemalloc_object_list = object_list_of(jemalloc_sources)


include_list = ' '.join(['-I' + 'duckdb/' + x for x in include_list])
include_list += ' -Ivendor'
include_list += ' -Iduckdb'
include_list += extension_list
include_list += debug_move_flag

if 'TREAT_WARNINGS_AS_ERRORS' in os.environ:
    include_list += ' -Werror'

# The jemalloc half of src/Makevars, which only the non-Windows build has:
# DuckDB does not build jemalloc on Windows, and the wrapper it would compile
# there stops with an #error. Which of the two Linux and macOS get is
# ./configure's to decide -- it writes Makevars.jemalloc on the build machine
# -- so all that is generated here is the include that reads that decision.
#
# The rule beneath it mirrors the ones above for Makevars.duckdb and
# Makevars.system-lib: a development tree that has not run configure still has
# something to include, because plain `include` is portable where `-include`
# is a GNU Make extension.
jemalloc_include = """
# This file is written by the configure script, which decides whether this
# platform is one DuckDB builds jemalloc for. An empty file is fine too for
# development, keeping an old timestamp to avoid pkgbuild removing all .o files.
Makevars.jemalloc:
\ttouch -r $$(ls -t *.cpp | head -n 1) "$@"

include Makevars.jemalloc
"""


def write_makevars(target, includes, link_flags_value, jemalloc):
    with open_utf8(os.path.join('src', 'Makevars.in'), 'r') as f:
        text = f.read()

    text = text.replace('{{ HEADER }}', 'Generated by rconfigure.py, do not edit by hand')
    text = text.replace('{{ INCLUDES }}', includes)
    if link_flags_value is None:
        text = text.replace('PKG_LIBS={{ LINK_FLAGS }}\n', '')
    else:
        text = text.replace('{{ LINK_FLAGS }}', link_flags_value)
    text = text.replace('{{ JEMALLOC }}\n', jemalloc)

    with open_utf8(os.path.join('src', target), 'w+') as f:
        f.write(text)


write_makevars(
    'Makevars',
    include_list,
    link_flags.strip() if libraries else None,
    jemalloc_include,
)

# same dance for Windows
write_makevars(
    'Makevars.win',
    include_list + " -DDUCKDB_PLATFORM_RTOOLS=1",
    "-lws2_32 $(DUCKDB_RSTRTMGR_LIB)",
    '',
)

text = "SOURCES=" + object_list + '\n'
text += "SOURCES_JEMALLOC=" + jemalloc_object_list + '\n'

with open_utf8(os.path.join('src', 'include', 'sources.mk'), 'w') as f:
    f.write(text)

extracted_version = extract_version_info()
generate_version_r_file(extracted_version)
